/' Patron ADAPTER '/

@startuml
!include ../format.puml

interface Rectangle {
    + draw()
}

class Client

class RectangleAdapter {
    + draw()
}

class LegacyRectangle {
    + render()
}

Rectangle <- Client
Rectangle <|-- RectangleAdapter
RectangleAdapter -> LegacyRectangle


@enduml
