/' Patron ADAPTER '/

@startuml
!include ../format.puml

interface Adapter {
    + operation()
}

class Client

class ConcreteAdapter {
    - adaptee
    + operation()
}

class Adaptee {
    + adaptedOperation()
}

Adapter <- Client
Adapter <|-- ConcreteAdapter
ConcreteAdapter -> Adaptee


@enduml
