/' DECORATOR '/

@startuml

abstract Component {
    + operation()
}

class ConcreteComponent {
    + operation()
}

class Decorator {
    + operation()
}

class ConcreteDecorator {
    - addedState
    + operation()
    + addedBehaviour()
}

Component <|- ConcreteComponent
Component <|-- Decorator
Component --* Decorator
Decorator <|- ConcreteDecorator

@enduml