/' FLYWEIGHT '/

@startuml

class FlyweightFactory {
    + getFlyweight()
}

abstract Flyweight {
    + operation(in extrinsicState)
}

class Client

class ConcreteFlyweight {
    - intrinsicState
    + operation(in extrinsicState)
}

class UnsharedConcreteFlyweight {
    - allState
    + operation(in extrinsicState)
}

hide empty members

FlyweightFactory *- Flyweight
Flyweight <|-- ConcreteFlyweight
Flyweight <|-- UnsharedConcreteFlyweight
FlyweightFactory <-- Client
ConcreteFlyweight <-- Client
UnsharedConcreteFlyweight <-- Client

@enduml