/' FLYWEIGHT '/

@startuml
!include ../format.puml

class ArbolFactory {
    - ArbolUnique arboles[]
    + getArbol()
}

class Client

class ArbolUnique {
    - Texture
    + operation(in extrinsicState)
}

class Arbol {
    - Vector2D pos
    - Color tint
    - *ArbolUnique
    + operation(in extrinsicState)
}

Client --> ArbolFactory
Client --> Arbol
Arbol -> ArbolFactory
ArbolFactory *-- ArbolUnique

@enduml