/' Patron FACTORY METHOD '/

@startuml
!include ../format.puml

class Creator {
    + factoryMethod()
    + anOperation()
}

class ConcreteCreator {
    + factoryMethod()
}

interface Product

class ConcreteProduct

Product <|-- ConcreteProduct
Creator <|-- ConcreteCreator
ConcreteProduct <. ConcreteCreator

@enduml