/' Patron PROTOTYPE '/

@startuml
!include ../format.puml

interface Prototype {
    + clone()
}

class Client

class ConcretePrototype1 {
    + clone()
}

class ConcretePrototype2 {
    + clone()
}

Client --> Prototype
Prototype <|-- ConcretePrototype1
Prototype <|-- ConcretePrototype2


@enduml